const LOADING = 'LOADING';
const GET_DATA_API = 'GET_DATA_API';
const ERROR = 'ERROR';
const NEW_NOTE_FLAG = 'NEW_NOTE_FLAG';
const TRAKING_NOTE = 'TRAKING_NOTE';
const NEW_LIST = 'NEW_LIST';
const NOTE_ID = 'NOTE_ID';
const BUTTON_STATUS = 'BUTTON_STATUS';

export { 
  LOADING, 
  GET_DATA_API, 
  ERROR,
  NEW_NOTE_FLAG,
  TRAKING_NOTE,
  NEW_LIST,
  NOTE_ID,
  BUTTON_STATUS
 };
 